export interface University {
  id: string
  region: string
  country: string
  name: string
}

export const universitiesByRegion: Record<string, University[]> = {
  "Africa": [
    { id: "af-eg-01", region: "Africa", country: "Egypt", name: "Cairo University" },
    { id: "af-eg-02", region: "Africa", country: "Egypt", name: "Egypt-Japan University of Science and Technology" },
    { id: "af-eg-03", region: "Africa", country: "Egypt", name: "The American University in Cairo" },
    { id: "af-ma-01", region: "Africa", country: "Morocco", name: "Al Akhawayn University" },
  ],
  "Asia": [
    { id: "as-bn-01", region: "Asia", country: "Brunei", name: "Universiti Brunei Darussalam" },
    { id: "as-cn-01", region: "Asia", country: "China", name: "Jilin University" },
    { id: "as-cn-02", region: "Asia", country: "China", name: "Nanjing University" },
    { id: "as-cn-03", region: "Asia", country: "China", name: "Nankai University" },
    { id: "as-cn-04", region: "Asia", country: "China", name: "Wuhan University" },
    { id: "as-hk-01", region: "Asia", country: "Hong Kong", name: "Hong Kong Baptist University" },
    { id: "as-hk-02", region: "Asia", country: "Hong Kong", name: "Lingnan University" },
    { id: "as-hk-03", region: "Asia", country: "Hong Kong", name: "The Chinese University of Hong Kong" },
    { id: "as-hk-04", region: "Asia", country: "Hong Kong", name: "The University of Hong Kong" },
    { id: "as-id-01", region: "Asia", country: "Indonesia", name: "Universitas Indonesia" },
    { id: "as-kr-01", region: "Asia", country: "Korea", name: "Ajou University" },
    { id: "as-kr-02", region: "Asia", country: "Korea", name: "Busan University of Foreign Studies" },
    { id: "as-kr-03", region: "Asia", country: "Korea", name: "Ewha Womans University" },
    { id: "as-kr-04", region: "Asia", country: "Korea", name: "Konkuk University" },
    { id: "as-kr-05", region: "Asia", country: "Korea", name: "Korea Advanced Institute of Science and Technology" },
    { id: "as-kr-06", region: "Asia", country: "Korea", name: "Korea University -College of Education" },
    { id: "as-kr-07", region: "Asia", country: "Korea", name: "Korea University -College of Liberal Arts" },
    { id: "as-kr-08", region: "Asia", country: "Korea", name: "Seoul National University" },
    { id: "as-kr-09", region: "Asia", country: "Korea", name: "Sogang University" },
    { id: "as-kr-10", region: "Asia", country: "Korea", name: "Yonsei University" },
    { id: "as-mo-01", region: "Asia", country: "Macau", name: "Macau University of Science and Technology" },
    { id: "as-mo-02", region: "Asia", country: "Macau", name: "University of Macau" },
    { id: "as-my-01", region: "Asia", country: "Malaysia", name: "Universiti Sains Malaysia" },
    { id: "as-my-02", region: "Asia", country: "Malaysia", name: "University of Malaya" },
    { id: "as-mn-01", region: "Asia", country: "Mongolia", name: "National University of Mongolia" },
    { id: "as-mn-02", region: "Asia", country: "Mongolia", name: "University of the Humanities" },
    { id: "as-ph-01", region: "Asia", country: "Philippines", name: "Ateneo de Manila University" },
    { id: "as-sg-01", region: "Asia", country: "Singapore", name: "Nanyang Technological University" },
    { id: "as-sg-02", region: "Asia", country: "Singapore", name: "National University of Singapore" },
    { id: "as-tw-01", region: "Asia", country: "Taiwan", name: "Fu Jen Catholic University" },
    { id: "as-tw-02", region: "Asia", country: "Taiwan", name: "Kainan University" },
    { id: "as-tw-03", region: "Asia", country: "Taiwan", name: "National Chengchi University" },
    { id: "as-tw-04", region: "Asia", country: "Taiwan", name: "National Chi Nan University" },
    { id: "as-tw-05", region: "Asia", country: "Taiwan", name: "National Taiwan Normal University" },
    { id: "as-tw-06", region: "Asia", country: "Taiwan", name: "National Taiwan University" },
    { id: "as-tw-07", region: "Asia", country: "Taiwan", name: "Tamkang University" },
    { id: "as-tw-08", region: "Asia", country: "Taiwan", name: "Yuan Ze University" },
    { id: "as-th-01", region: "Asia", country: "Thailand", name: "Chulalongkorn University" },
    { id: "as-th-02", region: "Asia", country: "Thailand", name: "Chulalongkorn University (BBA)" },
    { id: "as-th-03", region: "Asia", country: "Thailand", name: "Kasetsart University" },
    { id: "as-th-04", region: "Asia", country: "Thailand", name: "Mahidol University International College" },
    { id: "as-th-05", region: "Asia", country: "Thailand", name: "Thammasat University -Faculty of Political Science" },
    { id: "as-th-06", region: "Asia", country: "Thailand", name: "Thammasat University -Faculty of Economics" },
    { id: "as-vn-01", region: "Asia", country: "Vietnam", name: "Foreign Trade University" },
    { id: "as-vn-02", region: "Asia", country: "Vietnam", name: "VNU University of Economics and Business" },
  ],
  "Europe": [
    { id: "eu-at-01", region: "Europe", country: "Austria", name: "FH Joanneum University of Applied Sciences" },
    { id: "eu-be-01", region: "Europe", country: "Belgium", name: "Ghent University" },
    { id: "eu-be-02", region: "Europe", country: "Belgium", name: "Brussels School of Governance (formerly known as Vesalius College)" },
    { id: "eu-hr-01", region: "Europe", country: "Croatia", name: "Zagreb School of Economics and Management" },
    { id: "eu-cy-01", region: "Europe", country: "Cyprus", name: "University of Nicosia" },
    { id: "eu-cz-01", region: "Europe", country: "Czech Republic", name: "Masaryk University" },
    { id: "eu-dk-01", region: "Europe", country: "Denmark", name: "Aalborg University" },
    { id: "eu-dk-02", region: "Europe", country: "Denmark", name: "Aarhus University" },
    { id: "eu-ee-01", region: "Europe", country: "Estonia", name: "Tallinn University" },
    { id: "eu-fi-01", region: "Europe", country: "Finland", name: "Tampere University" },
    { id: "eu-fi-02", region: "Europe", country: "Finland", name: "University of Lapland" },
    { id: "eu-fi-03", region: "Europe", country: "Finland", name: "University of Eastern Finland" },
    { id: "eu-fi-04", region: "Europe", country: "Finland", name: "University of Vaasa" },
    { id: "eu-fr-01", region: "Europe", country: "France", name: "Burgundy School of Business" },
    { id: "eu-fr-02", region: "Europe", country: "France", name: "NEOMA Business School" },
    { id: "eu-fr-03", region: "Europe", country: "France", name: "Rennes 2 University" },
    { id: "eu-fr-04", region: "Europe", country: "France", name: "Rennes School of Business" },
    { id: "eu-fr-05", region: "Europe", country: "France", name: "Sciences Po Grenoble" },
    { id: "eu-fr-06", region: "Europe", country: "France", name: "Sciences Po Lille" },
    { id: "eu-fr-07", region: "Europe", country: "France", name: "Sciences Po Rennes" },
    { id: "eu-fr-08", region: "Europe", country: "France", name: "Toulouse Business School" },
    { id: "eu-fr-09", region: "Europe", country: "France", name: "University Toulouse - Jean Jaures" },
    { id: "eu-de-01", region: "Europe", country: "Germany", name: "Ludwigshafen University of Business and Society, University of Applied Sciences" },
    { id: "eu-de-02", region: "Europe", country: "Germany", name: "Philipps-Universitaet Marburg" },
    { id: "eu-de-03", region: "Europe", country: "Germany", name: "University of Bayreuth" },
    { id: "eu-de-04", region: "Europe", country: "Germany", name: "University of Passau" },
    { id: "eu-hu-01", region: "Europe", country: "Hungary", name: "University of Pecs" },
    { id: "eu-ie-01", region: "Europe", country: "Ireland", name: "Maynooth University" },
    { id: "eu-it-01", region: "Europe", country: "Italy", name: "Ca' Foscari University of Venice" },
    { id: "eu-it-02", region: "Europe", country: "Italy", name: "Sapienza University of Rome" },
    { id: "eu-it-03", region: "Europe", country: "Italy", name: "University of Bologna" },
    { id: "eu-it-04", region: "Europe", country: "Italy", name: "University of Ferrara" },
    { id: "eu-it-05", region: "Europe", country: "Italy", name: "University of Siena" },
    { id: "eu-it-06", region: "Europe", country: "Italy", name: "University of Turin" },
    { id: "eu-lv-01", region: "Europe", country: "Latvia", name: "University of Latvia" },
    { id: "eu-lt-01", region: "Europe", country: "Lithuania", name: "Vilnius University" },
    { id: "eu-lt-02", region: "Europe", country: "Lithuania", name: "Vytautas Magnus University" },
    { id: "eu-mt-01", region: "Europe", country: "Malta", name: "University of Malta" },
    { id: "eu-nl-01", region: "Europe", country: "Netherlands", name: "Amsterdam University of Applied Sciences" },
    { id: "eu-nl-02", region: "Europe", country: "Netherlands", name: "HAN University of Applied Sciences" },
    { id: "eu-nl-03", region: "Europe", country: "Netherlands", name: "Hanze University of Applied Sciences, Groningen" },
    { id: "eu-nl-04", region: "Europe", country: "Netherlands", name: "Leiden University" },
    { id: "eu-nl-05", region: "Europe", country: "Netherlands", name: "University College Utrecht" },
    { id: "eu-no-01", region: "Europe", country: "Norway", name: "NHH Norwegian School of Economics" },
    { id: "eu-no-02", region: "Europe", country: "Norway", name: "University of Agder" },
    { id: "eu-no-03", region: "Europe", country: "Norway", name: "University of Bergen" },
    { id: "eu-no-04", region: "Europe", country: "Norway", name: "University of Oslo" },
    { id: "eu-pl-01", region: "Europe", country: "Poland", name: "University of Lodz" },
    { id: "eu-pl-02", region: "Europe", country: "Poland", name: "Warsaw School of Economics" },
    { id: "eu-pt-01", region: "Europe", country: "Portugal", name: "ISCTE-Lisbon University Institute" },
    { id: "eu-pt-02", region: "Europe", country: "Portugal", name: "Universidade Catolica Portuguesa -Faculty of Economics and Management (Porto)" },
    { id: "eu-pt-03", region: "Europe", country: "Portugal", name: "Universidade Catolica Portuguesa -Faculty of Human Sciences (Lisbon)" },
    { id: "eu-pt-04", region: "Europe", country: "Portugal", name: "University of Porto" },
    { id: "eu-ro-01", region: "Europe", country: "Romania", name: "University of Bucharest" },
    { id: "eu-ru-01", region: "Europe", country: "Russia", name: "Far Eastern Federal University" },
    { id: "eu-ru-02", region: "Europe", country: "Russia", name: "International University in Moscow" },
    { id: "eu-ru-03", region: "Europe", country: "Russia", name: "Lomonosov Moscow State University, Institute of Asian and African Studies" },
    { id: "eu-ru-04", region: "Europe", country: "Russia", name: "National Research University Higher School of Economics (Moscow)" },
    { id: "eu-ru-05", region: "Europe", country: "Russia", name: "National Research University Higher School of Economics (St. Petersburg)" },
    { id: "eu-sk-01", region: "Europe", country: "Slovakia", name: "Comenius University" },
    { id: "eu-si-01", region: "Europe", country: "Slovenia", name: "University of Ljubljana" },
    { id: "eu-es-01", region: "Europe", country: "Spain", name: "Universidad de Alicante" },
    { id: "eu-es-02", region: "Europe", country: "Spain", name: "Universidad de Malaga" },
    { id: "eu-es-03", region: "Europe", country: "Spain", name: "Universitat Autonoma de Barcelona" },
    { id: "eu-es-04", region: "Europe", country: "Spain", name: "University of Burgos" },
    { id: "eu-es-05", region: "Europe", country: "Spain", name: "University of Jaen" },
    { id: "eu-se-01", region: "Europe", country: "Sweden", name: "Linkoping University" },
    { id: "eu-se-02", region: "Europe", country: "Sweden", name: "Linnaeus University" },
    { id: "eu-se-03", region: "Europe", country: "Sweden", name: "Orebro University" },
    { id: "eu-ch-01", region: "Europe", country: "Switzerland", name: "Eastern Switzerland University of Applied Sciences" },
    { id: "eu-ch-02", region: "Europe", country: "Switzerland", name: "Zurich University of Applied Sciences Winterthur" },
    { id: "eu-gb-01", region: "Europe", country: "U.K.", name: "Keele University" },
    { id: "eu-gb-02", region: "Europe", country: "U.K.", name: "Newcastle University" },
    { id: "eu-gb-03", region: "Europe", country: "U.K.", name: "The University of Sheffield" },
    { id: "eu-gb-04", region: "Europe", country: "U.K.", name: "University of Aberdeen" },
    { id: "eu-gb-05", region: "Europe", country: "U.K.", name: "University of Lancashire" },
    { id: "eu-gb-06", region: "Europe", country: "U.K.", name: "University of East Anglia" },
    { id: "eu-gb-07", region: "Europe", country: "U.K.", name: "The University of Edinburgh" },
    { id: "eu-gb-08", region: "Europe", country: "U.K.", name: "University of Essex" },
    { id: "eu-gb-09", region: "Europe", country: "U.K.", name: "University of Exeter" },
    { id: "eu-gb-10", region: "Europe", country: "U.K.", name: "University of Leeds" },
    { id: "eu-gb-11", region: "Europe", country: "U.K.", name: "University of Sussex" },
  ],
  "North America": [
    { id: "na-bs-01", region: "North America", country: "The Bahamas", name: "University of The Bahamas" },
    { id: "na-ca-01", region: "North America", country: "Canada", name: "Universite Laval" },
    { id: "na-ca-02", region: "North America", country: "Canada", name: "University of Manitoba" },
    { id: "na-ca-03", region: "North America", country: "Canada", name: "University of Manitoba Asper School of Business" },
    { id: "na-ca-04", region: "North America", country: "Canada", name: "University of Toronto" },
    { id: "na-ca-05", region: "North America", country: "Canada", name: "University of Victoria" },
    { id: "na-ca-06", region: "North America", country: "Canada", name: "University of Waterloo" },
    { id: "na-ca-07", region: "North America", country: "Canada", name: "University of Windsor" },
    { id: "na-ca-08", region: "North America", country: "Canada", name: "Wilfrid Laurier University" },
    { id: "na-mx-01", region: "North America", country: "Mexico", name: "The University of Colima" },
    { id: "na-us-01", region: "North America", country: "U.S.A.", name: "Alverno College" },
    { id: "na-us-02", region: "North America", country: "U.S.A.", name: "Arizona State University" },
    { id: "na-us-03", region: "North America", country: "U.S.A.", name: "Ball State University" },
    { id: "na-us-04", region: "North America", country: "U.S.A.", name: "Beloit College" },
    { id: "na-us-05", region: "North America", country: "U.S.A.", name: "Centre College" },
    { id: "na-us-06", region: "North America", country: "U.S.A.", name: "Dickinson College" },
    { id: "na-us-07", region: "North America", country: "U.S.A.", name: "Drexel University" },
    { id: "na-us-08", region: "North America", country: "U.S.A.", name: "Eastern Oregon University (*part of IE3)" },
    { id: "na-us-09", region: "North America", country: "U.S.A.", name: "George Mason University" },
    { id: "na-us-10", region: "North America", country: "U.S.A.", name: "Gonzaga University" },
    { id: "na-us-11", region: "North America", country: "U.S.A.", name: "Hamline University" },
    { id: "na-us-12", region: "North America", country: "U.S.A.", name: "Hampden-Sydney College" },
    { id: "na-us-13", region: "North America", country: "U.S.A.", name: "High Point University" },
    { id: "na-us-14", region: "North America", country: "U.S.A.", name: "IE3 Global" },
    { id: "na-us-15", region: "North America", country: "U.S.A.", name: "Ithaca College" },
    { id: "na-us-16", region: "North America", country: "U.S.A.", name: "Knox College" },
    { id: "na-us-17", region: "North America", country: "U.S.A.", name: "Lincoln Memorial University" },
    { id: "na-us-18", region: "North America", country: "U.S.A.", name: "Lyon College" },
    { id: "na-us-19", region: "North America", country: "U.S.A.", name: "Marist College" },
    { id: "na-us-20", region: "North America", country: "U.S.A.", name: "Millsaps College" },
    { id: "na-us-21", region: "North America", country: "U.S.A.", name: "Mississippi State University" },
    { id: "na-us-22", region: "North America", country: "U.S.A.", name: "Monmouth College" },
    { id: "na-us-23", region: "North America", country: "U.S.A.", name: "Oregon Institute of Technology (*part of IE3 Global)" },
    { id: "na-us-24", region: "North America", country: "U.S.A.", name: "Oregon State University (*part of IE3 Global)" },
    { id: "na-us-25", region: "North America", country: "U.S.A.", name: "Portland State University (*part of IE3 Global)" },
    { id: "na-us-26", region: "North America", country: "U.S.A.", name: "Presbyterian College" },
    { id: "na-us-27", region: "North America", country: "U.S.A.", name: "San Diego State University" },
    { id: "na-us-28", region: "North America", country: "U.S.A.", name: "San Francisco State University" },
    { id: "na-us-29", region: "North America", country: "U.S.A.", name: "Southern Oregon University (*part of IE3 Global)" },
    { id: "na-us-30", region: "North America", country: "U.S.A.", name: "St. Cloud State University" },
    { id: "na-us-31", region: "North America", country: "U.S.A.", name: "St. Mary's College of California" },
    { id: "na-us-32", region: "North America", country: "U.S.A.", name: "St. Mary's College of Maryland" },
    { id: "na-us-33", region: "North America", country: "U.S.A.", name: "State University of New York at Oswego" },
    { id: "na-us-34", region: "North America", country: "U.S.A.", name: "The College of William and Mary" },
    { id: "na-us-35", region: "North America", country: "U.S.A.", name: "The George Washington University" },
    { id: "na-us-36", region: "North America", country: "U.S.A.", name: "The University of Hawaii at Manoa" },
    { id: "na-us-37", region: "North America", country: "U.S.A.", name: "The University of Kentucky" },
    { id: "na-us-38", region: "North America", country: "U.S.A.", name: "The University of New Mexico" },
    { id: "na-us-39", region: "North America", country: "U.S.A.", name: "Towson University" },
    { id: "na-us-40", region: "North America", country: "U.S.A.", name: "Union College" },
    { id: "na-us-41", region: "North America", country: "U.S.A.", name: "University of California Berkeley" },
    { id: "na-us-42", region: "North America", country: "U.S.A.", name: "University of California Davis" },
    { id: "na-us-43", region: "North America", country: "U.S.A.", name: "University of Colorado at Boulder" },
    { id: "na-us-44", region: "North America", country: "U.S.A.", name: "University of Denver" },
    { id: "na-us-45", region: "North America", country: "U.S.A.", name: "University of Illinois at Urbana-Champaign" },
    { id: "na-us-46", region: "North America", country: "U.S.A.", name: "University of Maine at Farmington" },
    { id: "na-us-47", region: "North America", country: "U.S.A.", name: "University of Mary Washington" },
    { id: "na-us-48", region: "North America", country: "U.S.A.", name: "University of Mount Union" },
    { id: "na-us-49", region: "North America", country: "U.S.A.", name: "University of Northern Iowa" },
    { id: "na-us-50", region: "North America", country: "U.S.A.", name: "University of Oregon" },
    { id: "na-us-51", region: "North America", country: "U.S.A.", name: "University of Richmond" },
    { id: "na-us-52", region: "North America", country: "U.S.A.", name: "University of South Florida" },
    { id: "na-us-53", region: "North America", country: "U.S.A.", name: "University of Utah" },
    { id: "na-us-54", region: "North America", country: "U.S.A.", name: "Ursinus College" },
    { id: "na-us-55", region: "North America", country: "U.S.A.", name: "Washington & Jefferson College" },
    { id: "na-us-56", region: "North America", country: "U.S.A.", name: "Western Oregon University (*part of IE3 Global)" },
    { id: "na-us-57", region: "North America", country: "U.S.A.", name: "Western Washington University" },
    { id: "na-us-58", region: "North America", country: "U.S.A.", name: "Winona State University" },
  ],
  "Oceania": [
    { id: "oc-au-01", region: "Oceania", country: "Australia", name: "Deakin University" },
    { id: "oc-au-02", region: "Oceania", country: "Australia", name: "Griffith University" },
    { id: "oc-au-03", region: "Oceania", country: "Australia", name: "La Trobe University" },
    { id: "oc-au-04", region: "Oceania", country: "Australia", name: "Macquarie University" },
    { id: "oc-au-05", region: "Oceania", country: "Australia", name: "Swinburne University of Technology" },
    { id: "oc-au-06", region: "Oceania", country: "Australia", name: "The Australian National University" },
    { id: "oc-au-07", region: "Oceania", country: "Australia", name: "The University of New South Wales" },
    { id: "oc-au-08", region: "Oceania", country: "Australia", name: "The University of Sydney" },
    { id: "oc-au-09", region: "Oceania", country: "Australia", name: "The University of Western Australia" },
    { id: "oc-au-10", region: "Oceania", country: "Australia", name: "The University of the Sunshine Coast" },
    { id: "oc-au-11", region: "Oceania", country: "Australia", name: "University of Southern Queensland" },
    { id: "oc-nz-01", region: "Oceania", country: "New Zealand", name: "University of Canterbury" },
    { id: "oc-nz-02", region: "Oceania", country: "New Zealand", name: "Victoria University of Wellington" },
  ],
  "South America": [
    { id: "sa-ar-01", region: "South America", country: "Argentina", name: "Universidad Torcuato di Tella" },
    { id: "sa-cl-01", region: "South America", country: "Chile", name: "Universidad Adolfo Ibanez" },
    { id: "sa-pe-01", region: "South America", country: "Peru", name: "Universidad San Ignacio De Loyola" },
    { id: "sa-pe-02", region: "South America", country: "Peru", name: "Universidad del Pacifico" },
  ],
}

export const allUniversities = Object.values(universitiesByRegion).flat()

export const regions = Object.keys(universitiesByRegion)


